# **W3 Resources Pandas Practice Problems**
- https://www.w3resource.com/python-exercises/pandas/index-data-series.php

## **Pandas Series**

In [2]:
import pandas as pd

1. Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [270]:
series = pd.Series([1,2,3,4,5,6,10])
series

0     1
1     2
2     3
3     4
4     5
5     6
6    10
dtype: int64

2. Write a Pandas program to convert a Panda module Series to Python list and it's type.

In [271]:
serlist = series.tolist()
serlist

[1, 2, 3, 4, 5, 6, 10]

3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [272]:
ser1 = pd.Series([2, 4, 6, 8, 10])
ser2 = pd.Series([1, 3, 5, 7, 9])

print(ser1, ser2)

add = ser1 + ser2;print("\nAdd"); print(add)
sub = ser1-ser2; print("\nSubtract");print(sub)
mul = ser1*ser2; print("\nMultiply");print(mul)
div = ser1/ser2; print("\nDivide");print(div)

0     2
1     4
2     6
3     8
4    10
dtype: int64 0    1
1    3
2    5
3    7
4    9
dtype: int64

Add
0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtract
0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiply
0     2
1    12
2    30
3    56
4    90
dtype: int64

Divide
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


4. Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [273]:
ser1 == ser2

0    False
1    False
2    False
3    False
4    False
dtype: bool

5. Write a Pandas program to convert a dictionary to a Pandas series.

Sample Series: 
Original dictionary:

        {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64 

In [274]:
dict1 = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

ser = pd.Series(dict1); ser

a    100
b    200
c    300
d    400
e    800
dtype: int64

6. Write a Pandas program to convert a NumPy array to a Pandas series.

Sample Series: 
  NumPy array:
  
        [10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64 

In [275]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)
ser1 = pd.Series(arr1); ser1


[10 20 30 40 50]


0    10
1    20
2    30
3    40
4    50
dtype: int32

7. Write a Pandas program to change the data type of given a column or a Series.


In [276]:
ser1 = pd.Series([1,300,'Python','100', 250.3])
print(ser1)
# print(ser1.astype('Int32'))   
ser2 =  pd.to_numeric(ser1, errors='coerce')
ser2

0         1
1       300
2    Python
3       100
4     250.3
dtype: object


0      1.0
1    300.0
2      NaN
3    100.0
4    250.3
dtype: float64

9. Write a Pandas program to convert a given Series to an array.



In [277]:
arr2 = np.array(ser1); print(arr2)

[1 300 'Python' '100' 250.3]


10. Write a Pandas program to convert Series of lists to one Series.



In [278]:
import pandas as pd
lis1 = ['Red', 'Green', 'White']
lis2 = ['Red', 'Black']
lis3 = ['Yellow']

combined = pd.Series(lis1 + lis2 + lis3)

print(combined)

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


In [279]:
# ser1 = pd.Series(['Red', 'Green', 'White'],
# ['Red', 'Black'],
# ['Yellow'])

# # ser1 = pd.Series()
# # for i in (lis1, lis2, lis3):
# #     ser1.add(i)
# # print(ser1)

# ser1 = ser1.apply(pd.Series).stack().reset_index(drop = True)
# ser1

## **Pandas DataFrame**

1.Write a Pandas program to create a dataframe from a dictionary and display it.
Sample data: 

    {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

In [280]:
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}); df

X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.
Sample Python dictionary data and list labels:

        exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
        labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [281]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, labels);df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

3. Write a Pandas program to display a summary of the basic information about a specified DataFrame and its data.
Sample Python dictionary data and list labels:

        exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
        labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [282]:
exam_data= {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


df = pd.DataFrame(exam_data, labels); print(df)

df.info()

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


4. Write a Pandas program to get the first 3 rows of a given DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [283]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, labels)
df[:3]

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

5. Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [284]:
df[['name', 'score']]

name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

6. Write a Pandas program to select the specified columns and rows from a given data frame.
Sample Python dictionary data and list labels:
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [285]:
df.head()

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no

In [286]:
df.iloc[[1,3,5,6], 0:2]

name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

7. Write a  Pandas program to select the rows where the number of attempts in the examination is greater than 2.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [287]:
df[df['attempts']>2]

name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

8. Write a Pandas program to count the number of rows and columns of a DataFrame.
Sample  Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [288]:
df.shape

(10, 4)

In [289]:
print("rows = ", len(df.axes[0])); print("cols = ", len(df.axes[1]))

rows =  10
cols =  4


9. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [290]:
df[df['score'].isna()]

name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

10. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [291]:
df[df['score'].between(15,20)]

name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

11. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [292]:
df[(df['attempts']<2) & (df['score']>15)]

name  score  attempts qualify
j  Jonas   19.0         1     yes

12. Write a Pandas program to change the score in row 'd' to 11.5.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [293]:
df.loc ['d', 'score'] = 11.5
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

13. Write a  Pandas program to calculate the sum of the examination attempts by the students.

In [294]:
sum(df['attempts']);df['attempts'].sum()

19

14. Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.

In [295]:
df['score'].mean()

13.333333333333334

15. Write a Pandas program to append a new row 'k' to data frame with given values for each column. Now delete the new row and return the original DataFrame.
Sample Python dictionary data and list labels:

In [296]:
df.loc  ['k'] = ['Krishna',20,1, 'yes' ]; df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k    Krishna   20.0         1     yes

In [297]:
df.drop('j', inplace=True); df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
k    Krishna   20.0         1     yes

16. Write a Pandas program to sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order.

In [298]:
df.sort_values(by=['name', 'score'], ascending=[False, True])

name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
k    Krishna   20.0         1     yes
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

17. Write a  Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

In [299]:
df['qualify'] = df['qualify'].map({'yes':True, 'no':False}); df

name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James   11.5         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
k    Krishna   20.0         1     True

18. Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.

In [300]:
df['name'].replace('James', 'Suresh', inplace=True); df

C:\Users\RKC\AppData\Local\Temp\ipykernel_23120\3076892445.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['name'].replace('James', 'Suresh', inplace=True); df


name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d     Suresh   11.5         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
k    Krishna   20.0         1     True

19. Write a Pandas program to delete the 'attempts' column from the DataFrame.

In [301]:
df.drop(columns=['attempts'])

name  score  qualify
a  Anastasia   12.5     True
b       Dima    9.0    False
c  Katherine   16.5     True
d     Suresh   11.5    False
e      Emily    9.0    False
f    Michael   20.0     True
g    Matthew   14.5     True
h      Laura    NaN    False
i      Kevin    8.0    False
k    Krishna   20.0     True

In [302]:
dfpop = df.copy()
dfpop.pop('attempts'); dfpop

name  score  qualify
a  Anastasia   12.5     True
b       Dima    9.0    False
c  Katherine   16.5     True
d     Suresh   11.5    False
e      Emily    9.0    False
f    Michael   20.0     True
g    Matthew   14.5     True
h      Laura    NaN    False
i      Kevin    8.0    False
k    Krishna   20.0     True

20. Write a Pandas program to insert a new column in existing DataFrame.

In [303]:
df['Percentage'] = (df['score'] / 20)*100; df

name  score  attempts  qualify  Percentage
a  Anastasia   12.5         1     True        62.5
b       Dima    9.0         3    False        45.0
c  Katherine   16.5         2     True        82.5
d     Suresh   11.5         3    False        57.5
e      Emily    9.0         2    False        45.0
f    Michael   20.0         3     True       100.0
g    Matthew   14.5         1     True        72.5
h      Laura    NaN         1    False         NaN
i      Kevin    8.0         2    False        40.0
k    Krishna   20.0         1     True       100.0

21. Write a Pandas program to iterate over rows in a DataFrame.
Sample Python dictionary data and list labels:
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]

In [304]:
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]

In [305]:
df = pd.DataFrame(exam_data); df

name  score
0  Anastasia   12.5
1       Dima    9.0
2  Katherine   16.5

In [306]:
for name, score in df.iterrows():
    print(name, " ", score)

0   name     Anastasia
score         12.5
Name: 0, dtype: object
1   name     Dima
score     9.0
Name: 1, dtype: object
2   name     Katherine
score         16.5
Name: 2, dtype: object


In [307]:
for index, row in df.iterrows():
    print(row['name'], " ", row['score'])

Anastasia   12.5
Dima   9.0
Katherine   16.5


22. Write a Pandas program to get list from DataFrame column headers.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [308]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, labels); df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [309]:
print(df.columns.values)

for i in df.columns.values:
    print(i, end=" ; ")

['name' 'score' 'attempts' 'qualify']
name ; score ; attempts ; qualify ; 

23. Write a Pandas program to rename columns of a given DataFrame

In [310]:
df.rename(columns={'name': 'FullName'})

FullName  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

24. Write a Pandas program to select rows from a given DataFrame based on values in some columns.

In [311]:
df.where(df['score']>15)

name  score  attempts qualify
a        NaN    NaN       NaN     NaN
b        NaN    NaN       NaN     NaN
c  Katherine   16.5       2.0     yes
d        NaN    NaN       NaN     NaN
e        NaN    NaN       NaN     NaN
f    Michael   20.0       3.0     yes
g        NaN    NaN       NaN     NaN
h        NaN    NaN       NaN     NaN
i        NaN    NaN       NaN     NaN
j      Jonas   19.0       1.0     yes

In [312]:
df.loc[df['score']>15]

name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

25. Write a Pandas program to change the order of a DataFrame columns.


In [313]:
df.columns

Index(['name', 'score', 'attempts', 'qualify'], dtype='object')

In [314]:
df[['attempts', 'qualify', 'score', 'name']]

attempts qualify  score       name
a         1     yes   12.5  Anastasia
b         3      no    9.0       Dima
c         2     yes   16.5  Katherine
d         3      no    NaN      James
e         2      no    9.0      Emily
f         3     yes   20.0    Michael
g         1     yes   14.5    Matthew
h         1      no    NaN      Laura
i         2      no    8.0      Kevin
j         1     yes   19.0      Jonas

27. Write a Pandas program to write a DataFrame to CSV file using tab separator.


In [315]:
df.to_csv("df_csv_tabsep.csv", sep="\t", index=False)

28. Write a Pandas program to count city wise number of people from a given of data set (city, name of the person).


In [316]:
df1 = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'city': ['California', 'Los Angeles', 'California', 'California', 'California', 'Los Angeles', 'Los Angeles', 'Georgia', 'Georgia', 'Los Angeles']}); df1

name         city
0  Anastasia   California
1       Dima  Los Angeles
2  Katherine   California
3      James   California
4      Emily   California
5    Michael  Los Angeles
6    Matthew  Los Angeles
7      Laura      Georgia
8      Kevin      Georgia
9      Jonas  Los Angeles

In [317]:
df1.groupby('city').size().reset_index(name='Number of people')

city  Number of people
0   California                 4
1      Georgia                 2
2  Los Angeles                 4

In [318]:
df1.groupby('city').count().reset_index()

city  name
0   California     4
1      Georgia     2
2  Los Angeles     4

32. Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.


In [320]:
df.fillna(0)

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    0.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    0.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

33. Write a Pandas program to convert index in a column of the given dataframe.


In [323]:
df.reset_index(level=0, inplace=True); df

level_0 index       name  score  attempts qualify
0        0     a  Anastasia   12.5         1     yes
1        1     b       Dima    9.0         3      no
2        2     c  Katherine   16.5         2     yes
3        3     d      James    NaN         3      no
4        4     e      Emily    9.0         2      no
5        5     f    Michael   20.0         3     yes
6        6     g    Matthew   14.5         1     yes
7        7     h      Laura    NaN         1      no
8        8     i      Kevin    8.0         2      no
9        9     j      Jonas   19.0         1     yes

In [326]:
print(df.to_string(index=False))

 level_0 index      name  score  attempts qualify
       0     a Anastasia   12.5         1     yes
       1     b      Dima    9.0         3      no
       2     c Katherine   16.5         2     yes
       3     d     James    NaN         3      no
       4     e     Emily    9.0         2      no
       5     f   Michael   20.0         3     yes
       6     g   Matthew   14.5         1     yes
       7     h     Laura    NaN         1      no
       8     i     Kevin    8.0         2      no
       9     j     Jonas   19.0         1     yes


34. Write a Pandas program to set a given value for particular cell in  DataFrame using index value.


In [329]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   level_0   10 non-null     int64  
 1   index     10 non-null     object 
 2   name      10 non-null     object 
 3   score     8 non-null      float64
 4   attempts  10 non-null     int64  
 5   qualify   10 non-null     object 
dtypes: float64(1), int64(2), object(3)
memory usage: 612.0+ bytes


In [327]:
df.set_value(8, 'score', 10.2)

AttributeError: 'DataFrame' object has no attribute 'set_value'

35. Write a Pandas program to count the NaN values in one or more columns in DataFrame.


In [334]:
df.isnull().sum()

level_0     0
index       0
name        0
score       2
attempts    0
qualify     0
dtype: int64

36. Write a Pandas program to drop a list of rows from a specified DataFrame.


37. Write a Pandas program to reset index in a given DataFrame.


38. Write a Pandas program to divide a DataFrame in a given ratio.


In [336]:
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
s2 = pd.Series(['10', '20', 'php', '30.12', '40'])

df = pd.concat([s1,s2], axis=1); df

0      1
0     100     10
1     200     20
2  python    php
3  300.12  30.12
4     400     40

40. Write a Pandas program to shuffle a given DataFrame rows.


In [339]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

df = pd.DataFrame(exam_data)

In [351]:
df.sample(frac=1)

name  score  attempts qualify
9      Jonas   19.0         1     yes
8      Kevin    8.0         2      no
1       Dima    9.0         3      no
3      James    NaN         3      no
7      Laura    NaN         1      no
6    Matthew   14.5         1     yes
2  Katherine   16.5         2     yes
5    Michael   20.0         3     yes
0  Anastasia   12.5         1     yes
4      Emily    9.0         2      no

41. Write a Pandas program to convert DataFrame column type from string to datetime.


In [352]:
s = pd.Series(['3/11/2000', '3/12/2000', '3/13/2000'])

In [353]:
df = pd.DataFrame(s); df

0
0  3/11/2000
1  3/12/2000
2  3/13/2000

In [359]:
df = pd.to_datetime(pd.Series(s)); df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: None
Non-Null Count  Dtype         
--------------  -----         
3 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 156.0 bytes


42. Write a Pandas program to rename a specific column name in a given DataFrame.


## **Pandas Indexing**

1. Write a Pandas program to display the default index and set a column as an Index in a given dataframe.

In [3]:
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4'],
    't_id':['t1', 't2', 't3', 't4', 't5', 't6']})

In [6]:
df.set_index('school_code')

class            name date_Of_Birth  weight  address t_id
school_code                                                          
s001            V  Alberto Franco    15/05/2002      35  street1   t1
s002            V    Gino Mcneill    17/05/2002      32  street2   t2
s003           VI     Ryan Parkes    16/02/1999      33  street3   t3
s001           VI    Eesha Hinton    25/09/1998      30  street1   t4
s002            V    Gino Mcneill    11/05/2002      31  street2   t5
s004           VI    David Parkes    15/09/1997      32  street4   t6

2. Write a Pandas program to create a multi Index frame using two columns and using an Index and a column.

In [7]:
df.columns

Index(['school_code', 'class', 'name', 'date_Of_Birth', 'weight', 'address',
       't_id'],
      dtype='object')

In [12]:
df.set_index(['class', 't_id'])

school_code            name date_Of_Birth  weight  address
class t_id                                                           
V     t1          s001  Alberto Franco    15/05/2002      35  street1
      t2          s002    Gino Mcneill    17/05/2002      32  street2
VI    t3          s003     Ryan Parkes    16/02/1999      33  street3
      t4          s001    Eesha Hinton    25/09/1998      30  street1
V     t5          s002    Gino Mcneill    11/05/2002      31  street2
VI    t6          s004    David Parkes    15/09/1997      32  street4

In [11]:
df.set_index([pd.Index([0,1,2,3,4,5]), 't_id'])

school_code class            name date_Of_Birth  weight  address
  t_id                                                                 
0 t1          s001     V  Alberto Franco    15/05/2002      35  street1
1 t2          s002     V    Gino Mcneill    17/05/2002      32  street2
2 t3          s003    VI     Ryan Parkes    16/02/1999      33  street3
3 t4          s001    VI    Eesha Hinton    25/09/1998      30  street1
4 t5          s002     V    Gino Mcneill    11/05/2002      31  street2
5 t6          s004    VI    David Parkes    15/09/1997      32  street4

6. Write a  Pandas program to create a dataframe indexing by date and time.

In [84]:
from datetime import datetime 
from random import randint
df_dates = pd.date_range(start=datetime.today(), freq='s', periods=10)
df = pd.DataFrame({'SalesAmt':[10,20,30,40,50,60,70,80,90,100]}, index=df_dates); df

SalesAmt
2024-12-22 20:20:10.559273        10
2024-12-22 20:20:11.559273        20
2024-12-22 20:20:12.559273        30
2024-12-22 20:20:13.559273        40
2024-12-22 20:20:14.559273        50
2024-12-22 20:20:15.559273        60
2024-12-22 20:20:16.559273        70
2024-12-22 20:20:17.559273        80
2024-12-22 20:20:18.559273        90
2024-12-22 20:20:19.559273       100

7. Write a Pandas program to create a dataframe and set a title or name of the index column.

In [109]:
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4'],
    't_id':['t1', 't2', 't3', 't4', 't5', 't6']})

In [110]:
df.index.name = 'Index_ Name'; df

school_code class            name date_Of_Birth  weight  address  \
Index_ Name                                                                    
0                  s001     V  Alberto Franco    15/05/2002      35  street1   
1                  s002     V    Gino Mcneill    17/05/2002      32  street2   
2                  s003    VI     Ryan Parkes    16/02/1999      33  street3   
3                  s001    VI    Eesha Hinton    25/09/1998      30  street1   
4                  s002     V    Gino Mcneill    11/05/2002      31  street2   
5                  s004    VI    David Parkes    15/09/1997      32  street4   

            t_id  
Index_ Name       
0             t1  
1             t2  
2             t3  
3             t4  
4             t5  
5             t6

8. Write a Pandas program to set value in a specific cell in a given dataframe using index.

In [111]:
df['name'].loc[5] = "Pranay Shah"; df

C:\Users\RKC\AppData\Local\Temp\ipykernel_21828\2450300567.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['name'].loc[5] = "Pranay Shah"; df
C:\Users\RKC\AppData\Local\Temp\ipykernel_21828\2450300567.py:1: SettingWithCopyWarning: 
A 

school_code class            name date_Of_Birth  weight  address  \
Index_ Name                                                                    
0                  s001     V  Alberto Franco    15/05/2002      35  street1   
1                  s002     V    Gino Mcneill    17/05/2002      32  street2   
2                  s003    VI     Ryan Parkes    16/02/1999      33  street3   
3                  s001    VI    Eesha Hinton    25/09/1998      30  street1   
4                  s002     V    Gino Mcneill    11/05/2002      31  street2   
5                  s004    VI     Pranay Shah    15/09/1997      32  street4   

            t_id  
Index_ Name       
0             t1  
1             t2  
2             t3  
3             t4  
4             t5  
5             t6

In [112]:
df.at[5, 'class'] = 'PostGrad'; df

school_code     class            name date_Of_Birth  weight  \
Index_ Name                                                               
0                  s001         V  Alberto Franco    15/05/2002      35   
1                  s002         V    Gino Mcneill    17/05/2002      32   
2                  s003        VI     Ryan Parkes    16/02/1999      33   
3                  s001        VI    Eesha Hinton    25/09/1998      30   
4                  s002         V    Gino Mcneill    11/05/2002      31   
5                  s004  PostGrad     Pranay Shah    15/09/1997      32   

             address t_id  
Index_ Name                
0            street1   t1  
1            street2   t2  
2            street3   t3  
3            street1   t4  
4            street2   t5  
5            street4   t6

9. Write a Pandas program to convert index of a given dataframe into a column.


In [113]:
df.reset_index(level=0, inplace = True); df

Index_ Name school_code     class            name date_Of_Birth  weight  \
0            0        s001         V  Alberto Franco    15/05/2002      35   
1            1        s002         V    Gino Mcneill    17/05/2002      32   
2            2        s003        VI     Ryan Parkes    16/02/1999      33   
3            3        s001        VI    Eesha Hinton    25/09/1998      30   
4            4        s002         V    Gino Mcneill    11/05/2002      31   
5            5        s004  PostGrad     Pranay Shah    15/09/1997      32   

   address t_id  
0  street1   t1  
1  street2   t2  
2  street3   t3  
3  street1   t4  
4  street2   t5  
5  street4   t6

## **Pandas Merging, Joining and Grouping**

1. Write a Pandas program to join the two given dataframes along rows and assign all data.

In [135]:
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'], 
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'], 
        'marks': [201, 200, 198, 219, 201]})

In [140]:
df = pd.concat([student_data1, student_data1]); df

student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199

2. Write a Pandas program to join the two given dataframes along columns and assign all data.

In [137]:
df = pd.concat([student_data1, student_data1], axis=1).reset_index(); df

index student_id              name  marks student_id              name  \
0      0         S1  Danniella Fenton    200         S1  Danniella Fenton   
1      1         S2      Ryder Storey    210         S2      Ryder Storey   
2      2         S3      Bryce Jensen    190         S3      Bryce Jensen   
3      3         S4         Ed Bernal    222         S4         Ed Bernal   
4      4         S5       Kwame Morin    199         S5       Kwame Morin   

   marks  
0    200  
1    210  
2    190  
3    222  
4    199

3. Write a Pandas program to append rows to an existing DataFrame and display the combined data.

In [141]:
df.loc[len(df)] = ['S6', 'Pranay Shah', 290]; df

student_id              name  marks
0          S1  Danniella Fenton    200
1          S2      Ryder Storey    210
2          S3      Bryce Jensen    190
3          S4         Ed Bernal    222
4          S5       Kwame Morin    199
0          S1  Danniella Fenton    200
1          S2      Ryder Storey    210
2          S3      Bryce Jensen    190
3          S4         Ed Bernal    222
4          S5       Kwame Morin    199
10         S6       Pranay Shah    290

4. Write a Pandas program to append a list of dictioneries or series to a existing DataFrame and display the combined data.

In [142]:
new_stu = {'student_id':'S7', 'name':'Pranay B Shah', 'marks':300}

df = pd.concat([df, pd.DataFrame([new_stu])], ignore_index=True); df

student_id              name  marks
0          S1  Danniella Fenton    200
1          S2      Ryder Storey    210
2          S3      Bryce Jensen    190
3          S4         Ed Bernal    222
4          S5       Kwame Morin    199
5          S1  Danniella Fenton    200
6          S2      Ryder Storey    210
7          S3      Bryce Jensen    190
8          S4         Ed Bernal    222
9          S5       Kwame Morin    199
10         S6       Pranay Shah    290
11         S7     Pranay B Shah    300